== {vcd-provider-full} Release Notes

{cfme} supports {vcd} with limited functionality. The {vcd} coverage
is limited to the following functionality:

*  Authorization
*  Inventory
*  Power Operations
*  Provisioning
*  Events

Due to the limited support of {vcd}, some functionalities are not straightforward. The most
exceptional is provisioning of a virtual machine which is only possible by instantiating a predefined vApp
template. More details on this matter can be found in <<VAppProvisioninVCD>> section.

=== Authorization
Authorization is a basic functionality that creates a link from {cfme-appliance} to {vcd-host} and enables collecting
data from {vcd-host}. Authorization is possible through {vcd}'s *organization* (tenant) accounts. More
details on adding a new provider are described in <<AddingAVMwareVCD>> section.

=== Inventory
{vcd-provider} inventories {vcd}'s entities, e.g. virtual machines, and persists them
into {cfme}' database. There is a gap between how {vcd} names entities and how are they named in
{cfme}. Below please find a mapping between the two.

[options="header",alt="Cloud provider entity mapping"]
|=====================================================================================
| CloudForms Convention.                   | {vcd} Convention.
| Instance                                 | Virtual Machine
| Image                                    | Virtual Machine Inside vApp Template
| Orchestration Stack                      | vApp
| Orchestration Template                   | vApp Template
| Availability Zone                        | Virtual Datacenter (VDC)
| (not mapped)                             | Organization
| *OrgVdcNet* Network & Subnet             | VDC Network
| *OrgVappNet* Network & Subnet            | vApp Network
| Network Port                             | Network Interface Card (NIC)
| Floating IP                              | External IP
|=====================================================================================

=== Power Operations
Power operations cover the control functionality over the virtual machines and vApps, similarly that you
expect from other providers.

.Service Operations
Supported service operations are:

 * Set retirement date of a service.
 * Retire service immediately.

NOTE: When retiring services all virtual machines in the service will be stopped and deleted.

.Virtual Machine Operations
Supported virtual machine operations are:

* Start virtual machine.
* Stop virtual machine.
* Suspend virtual machine.
* Create snapshot of a virtual machine.
* Revert virtual machine from a snapshot.
* Delete snapsthot.
* Delete virtual machine.

=== Provisioning
The major difference of {vcd} from other platforms is that it provisions all resources wrapped in
vApps. The images, virtual machines and vApp templates can be stored in catalogs, but only vApps can be provisioned directly.
To provision other resources, a corresponding vApp needs to be built first.

The {vcd-full} has limited functionality and does not support building or
changing vApps from within {cfme} directly, therefore the vApp templates need to be created in advance within
{vcd-host}. Provisioning process of existing vApp template is described in <<VAppProvisioninVCD>> section.


=== Events
Events from {vcd} can be published to AMQP broker which filters them per organization (tenant).
{cfme} supports an option to provide AMQP credentials for {vcd-provider} in order to consume messages from
AMQP broker. More details on how to configure eventing support can be found in <<EventMonitoringRabbitMQVCD>>
section.
